name: 릴리즈 노트 자동 작성

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_notion_page:
    runs-on: ubuntu-latest
    steps:
      - name: step2
        id: get-commits
        run: echo "commits=${{ join(github.event.commits.*.id, ',') }}" >> $GITHUB_OUTPUT

      - name: step3
        run: echo ${{ steps.get-commits.outputs.commits }}
