name: aaaaaa

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_notion_page:
    runs-on: ubuntu-latest
    steps:
      - name: Extract commit details
        id: get-commits
        run: |
          echo ${{ toJson(github.event) }}
          commits_json=$(jq -c '.commits' <<< "${{ toJson(github.event) }}")
          echo "commits=$commits_json" >> $GITHUB_OUTPUT

      - name: Run Python script
        run: |
          python "$GITHUB_WORKSPACE/.github/scripts/main.py" '${{ steps.get-commits.outputs.commits }}'
